language: java
jdk:
    - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer
notifications:
    webhooks:
        - http://octopull.rmhartog.me/api/travis/webhook
    before_install:
        - "[ \"$BUILD_PR_BRANCH\" = \"true\" ] && git checkout $TRAVIS_BRANCH && echo \"OCTOPULL_SHA=$(git rev-parse HEAD)\"; true"
env:
  - BUILD_PR_BRANCH=true
matrix:
  allow_failures:
    - env:
      - BUILD_PR_BRANCH=true
after_script:
  - echo "== CHECKSTYLE_RESULT ==" && cat "core/target/checkstyle-result.xml" && echo "== END_CHECKSTYLE_RESULT =="
  - echo "== PMD_RESULT ==" && cat "core/target/pmd.xml" && echo "== END_PMD_RESULT =="
  - echo "== FINDBUGS_RESULT ==" && cat "core/target/findbugsXml.xml" && echo "== END_FINDBUGS_RESULT =="